//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LookML.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GraphqlToTsql.CodeGen.LookML {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class LookMLLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		VIEW=1, SQL_TABLE_NAME=2, FIELD=3, SQL=4, LABEL=5, VIEW_LABEL=6, TYPE=7, 
		LINK=8, URL=9, DESCRIPTION=10, DRILL_FIELDS=11, DERIVED_TABLE=12, SQL_TRIGGER_VALUE=13, 
		SORTKEYS=14, STRING=15, QUOTED_STRING=16, TABLE_REF=17, WS=18, COMMENT=19, 
		DELIM=20, SEP=21, LBRACE=22, RBRACE=23;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"VIEW", "SQL_TABLE_NAME", "FIELD", "SQL", "LABEL", "VIEW_LABEL", "TYPE", 
		"LINK", "URL", "DESCRIPTION", "DRILL_FIELDS", "DERIVED_TABLE", "SQL_TRIGGER_VALUE", 
		"SORTKEYS", "STRING", "QUOTED_STRING", "TABLE_REF", "WS", "COMMENT", "DELIM", 
		"SEP", "LBRACE", "RBRACE"
	};


	public LookMLLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LookMLLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'view'", "'sql_table_name'", null, "'sql'", "'label'", "'view_label'", 
		"'type'", "'link'", "'url'", "'description'", "'drill_fields'", "'derived_table'", 
		"'sql_trigger_value'", "'sortkeys'", null, null, null, null, null, "';;'", 
		"':'", "'{'", "'}'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "VIEW", "SQL_TABLE_NAME", "FIELD", "SQL", "LABEL", "VIEW_LABEL", 
		"TYPE", "LINK", "URL", "DESCRIPTION", "DRILL_FIELDS", "DERIVED_TABLE", 
		"SQL_TRIGGER_VALUE", "SORTKEYS", "STRING", "QUOTED_STRING", "TABLE_REF", 
		"WS", "COMMENT", "DELIM", "SEP", "LBRACE", "RBRACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LookML.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LookMLLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x19', '\x107', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 'k', '\n', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x6', '\x10', '\xD3', '\n', '\x10', '\r', '\x10', '\xE', '\x10', 
		'\xD4', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\xD9', '\n', '\x11', 
		'\f', '\x11', '\xE', '\x11', '\xDC', '\v', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x6', '\x12', '\xEB', '\n', '\x12', '\r', '\x12', 
		'\xE', '\x12', '\xEC', '\x3', '\x13', '\x6', '\x13', '\xF0', '\n', '\x13', 
		'\r', '\x13', '\xE', '\x13', '\xF1', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\a', '\x14', '\xF8', '\n', '\x14', '\f', '\x14', 
		'\xE', '\x14', '\xFB', '\v', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\xDA', '\x2', 
		'\x19', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', 
		'\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', 
		'\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', 
		'\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', 
		'-', '\x18', '/', '\x19', '\x3', '\x2', '\x6', '\n', '\x2', '$', '$', 
		')', ',', '.', '\x31', '>', '@', '\x43', ']', '_', '_', '\x61', '\x61', 
		'\x63', '|', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\t', '\x2', '$', 
		'$', '\x30', '\x30', '<', '<', '\x43', '\\', '^', '^', '\x61', '\x61', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', 
		'\x10E', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x3', '\x31', '\x3', '\x2', '\x2', '\x2', '\x5', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'j', '\x3', '\x2', '\x2', '\x2', '\t', 'l', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'p', '\x3', '\x2', '\x2', '\x2', '\r', 
		'v', '\x3', '\x2', '\x2', '\x2', '\xF', '\x81', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x86', '\x3', '\x2', '\x2', '\x2', '\x13', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x17', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\xA8', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\xB6', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xC8', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\xD2', '\x3', '\x2', '\x2', '\x2', '!', '\xD6', 
		'\x3', '\x2', '\x2', '\x2', '#', '\xDF', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\'', '\xF5', '\x3', '\x2', '\x2', 
		'\x2', ')', '\xFE', '\x3', '\x2', '\x2', '\x2', '+', '\x101', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x103', '\x3', '\x2', '\x2', '\x2', '/', '\x105', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\a', 'x', '\x2', '\x2', '\x32', 
		'\x33', '\a', 'k', '\x2', '\x2', '\x33', '\x34', '\a', 'g', '\x2', '\x2', 
		'\x34', '\x35', '\a', 'y', '\x2', '\x2', '\x35', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x36', '\x37', '\a', 'u', '\x2', '\x2', '\x37', '\x38', 
		'\a', 's', '\x2', '\x2', '\x38', '\x39', '\a', 'n', '\x2', '\x2', '\x39', 
		':', '\a', '\x61', '\x2', '\x2', ':', ';', '\a', 'v', '\x2', '\x2', ';', 
		'<', '\a', '\x63', '\x2', '\x2', '<', '=', '\a', '\x64', '\x2', '\x2', 
		'=', '>', '\a', 'n', '\x2', '\x2', '>', '?', '\a', 'g', '\x2', '\x2', 
		'?', '@', '\a', '\x61', '\x2', '\x2', '@', '\x41', '\a', 'p', '\x2', '\x2', 
		'\x41', '\x42', '\a', '\x63', '\x2', '\x2', '\x42', '\x43', '\a', 'o', 
		'\x2', '\x2', '\x43', '\x44', '\a', 'g', '\x2', '\x2', '\x44', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x66', '\x2', '\x2', 
		'\x46', 'G', '\a', 'k', '\x2', '\x2', 'G', 'H', '\a', 'o', '\x2', '\x2', 
		'H', 'I', '\a', 'g', '\x2', '\x2', 'I', 'J', '\a', 'p', '\x2', '\x2', 
		'J', 'K', '\a', 'u', '\x2', '\x2', 'K', 'L', '\a', 'k', '\x2', '\x2', 
		'L', 'M', '\a', 'q', '\x2', '\x2', 'M', 'k', '\a', 'p', '\x2', '\x2', 
		'N', 'O', '\a', '\x66', '\x2', '\x2', 'O', 'P', '\a', 'k', '\x2', '\x2', 
		'P', 'Q', '\a', 'o', '\x2', '\x2', 'Q', 'R', '\a', 'g', '\x2', '\x2', 
		'R', 'S', '\a', 'p', '\x2', '\x2', 'S', 'T', '\a', 'u', '\x2', '\x2', 
		'T', 'U', '\a', 'k', '\x2', '\x2', 'U', 'V', '\a', 'q', '\x2', '\x2', 
		'V', 'W', '\a', 'p', '\x2', '\x2', 'W', 'X', '\a', '\x61', '\x2', '\x2', 
		'X', 'Y', '\a', 'i', '\x2', '\x2', 'Y', 'Z', '\a', 't', '\x2', '\x2', 
		'Z', '[', '\a', 'q', '\x2', '\x2', '[', '\\', '\a', 'w', '\x2', '\x2', 
		'\\', 'k', '\a', 'r', '\x2', '\x2', ']', '^', '\a', 'o', '\x2', '\x2', 
		'^', '_', '\a', 'g', '\x2', '\x2', '_', '`', '\a', '\x63', '\x2', '\x2', 
		'`', '\x61', '\a', 'u', '\x2', '\x2', '\x61', '\x62', '\a', 'w', '\x2', 
		'\x2', '\x62', '\x63', '\a', 't', '\x2', '\x2', '\x63', 'k', '\a', 'g', 
		'\x2', '\x2', '\x64', '\x65', '\a', 'h', '\x2', '\x2', '\x65', '\x66', 
		'\a', 'k', '\x2', '\x2', '\x66', 'g', '\a', 'n', '\x2', '\x2', 'g', 'h', 
		'\a', 'v', '\x2', '\x2', 'h', 'i', '\a', 'g', '\x2', '\x2', 'i', 'k', 
		'\a', 't', '\x2', '\x2', 'j', '\x45', '\x3', '\x2', '\x2', '\x2', 'j', 
		'N', '\x3', '\x2', '\x2', '\x2', 'j', ']', '\x3', '\x2', '\x2', '\x2', 
		'j', '\x64', '\x3', '\x2', '\x2', '\x2', 'k', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'l', 'm', '\a', 'u', '\x2', '\x2', 'm', 'n', '\a', 's', '\x2', 
		'\x2', 'n', 'o', '\a', 'n', '\x2', '\x2', 'o', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'q', '\a', 'n', '\x2', '\x2', 'q', 'r', '\a', '\x63', '\x2', 
		'\x2', 'r', 's', '\a', '\x64', '\x2', '\x2', 's', 't', '\a', 'g', '\x2', 
		'\x2', 't', 'u', '\a', 'n', '\x2', '\x2', 'u', '\f', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\a', 'x', '\x2', '\x2', 'w', 'x', '\a', 'k', '\x2', 
		'\x2', 'x', 'y', '\a', 'g', '\x2', '\x2', 'y', 'z', '\a', 'y', '\x2', 
		'\x2', 'z', '{', '\a', '\x61', '\x2', '\x2', '{', '|', '\a', 'n', '\x2', 
		'\x2', '|', '}', '\a', '\x63', '\x2', '\x2', '}', '~', '\a', '\x64', '\x2', 
		'\x2', '~', '\x7F', '\a', 'g', '\x2', '\x2', '\x7F', '\x80', '\a', 'n', 
		'\x2', '\x2', '\x80', '\xE', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'v', '\x2', '\x2', '\x82', '\x83', '\a', '{', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'r', '\x2', '\x2', '\x84', '\x85', '\a', 'g', '\x2', '\x2', 
		'\x85', '\x10', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', 'n', 
		'\x2', '\x2', '\x87', '\x88', '\a', 'k', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'p', '\x2', '\x2', '\x89', '\x8A', '\a', 'm', '\x2', '\x2', '\x8A', 
		'\x12', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 'w', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', 't', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'n', '\x2', '\x2', '\x8E', '\x14', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\a', '\x66', '\x2', '\x2', '\x90', '\x91', '\a', 'g', '\x2', 
		'\x2', '\x91', '\x92', '\a', 'u', '\x2', '\x2', '\x92', '\x93', '\a', 
		'\x65', '\x2', '\x2', '\x93', '\x94', '\a', 't', '\x2', '\x2', '\x94', 
		'\x95', '\a', 'k', '\x2', '\x2', '\x95', '\x96', '\a', 'r', '\x2', '\x2', 
		'\x96', '\x97', '\a', 'v', '\x2', '\x2', '\x97', '\x98', '\a', 'k', '\x2', 
		'\x2', '\x98', '\x99', '\a', 'q', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'p', '\x2', '\x2', '\x9A', '\x16', '\x3', '\x2', '\x2', '\x2', '\x9B', 
		'\x9C', '\a', '\x66', '\x2', '\x2', '\x9C', '\x9D', '\a', 't', '\x2', 
		'\x2', '\x9D', '\x9E', '\a', 'k', '\x2', '\x2', '\x9E', '\x9F', '\a', 
		'n', '\x2', '\x2', '\x9F', '\xA0', '\a', 'n', '\x2', '\x2', '\xA0', '\xA1', 
		'\a', '\x61', '\x2', '\x2', '\xA1', '\xA2', '\a', 'h', '\x2', '\x2', '\xA2', 
		'\xA3', '\a', 'k', '\x2', '\x2', '\xA3', '\xA4', '\a', 'g', '\x2', '\x2', 
		'\xA4', '\xA5', '\a', 'n', '\x2', '\x2', '\xA5', '\xA6', '\a', '\x66', 
		'\x2', '\x2', '\xA6', '\xA7', '\a', 'u', '\x2', '\x2', '\xA7', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', '\x66', '\x2', '\x2', 
		'\xA9', '\xAA', '\a', 'g', '\x2', '\x2', '\xAA', '\xAB', '\a', 't', '\x2', 
		'\x2', '\xAB', '\xAC', '\a', 'k', '\x2', '\x2', '\xAC', '\xAD', '\a', 
		'x', '\x2', '\x2', '\xAD', '\xAE', '\a', 'g', '\x2', '\x2', '\xAE', '\xAF', 
		'\a', '\x66', '\x2', '\x2', '\xAF', '\xB0', '\a', '\x61', '\x2', '\x2', 
		'\xB0', '\xB1', '\a', 'v', '\x2', '\x2', '\xB1', '\xB2', '\a', '\x63', 
		'\x2', '\x2', '\xB2', '\xB3', '\a', '\x64', '\x2', '\x2', '\xB3', '\xB4', 
		'\a', 'n', '\x2', '\x2', '\xB4', '\xB5', '\a', 'g', '\x2', '\x2', '\xB5', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', 'u', '\x2', 
		'\x2', '\xB7', '\xB8', '\a', 's', '\x2', '\x2', '\xB8', '\xB9', '\a', 
		'n', '\x2', '\x2', '\xB9', '\xBA', '\a', '\x61', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', 'v', '\x2', '\x2', '\xBB', '\xBC', '\a', 't', '\x2', '\x2', 
		'\xBC', '\xBD', '\a', 'k', '\x2', '\x2', '\xBD', '\xBE', '\a', 'i', '\x2', 
		'\x2', '\xBE', '\xBF', '\a', 'i', '\x2', '\x2', '\xBF', '\xC0', '\a', 
		'g', '\x2', '\x2', '\xC0', '\xC1', '\a', 't', '\x2', '\x2', '\xC1', '\xC2', 
		'\a', '\x61', '\x2', '\x2', '\xC2', '\xC3', '\a', 'x', '\x2', '\x2', '\xC3', 
		'\xC4', '\a', '\x63', '\x2', '\x2', '\xC4', '\xC5', '\a', 'n', '\x2', 
		'\x2', '\xC5', '\xC6', '\a', 'w', '\x2', '\x2', '\xC6', '\xC7', '\a', 
		'g', '\x2', '\x2', '\xC7', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xC9', '\a', 'u', '\x2', '\x2', '\xC9', '\xCA', '\a', 'q', '\x2', '\x2', 
		'\xCA', '\xCB', '\a', 't', '\x2', '\x2', '\xCB', '\xCC', '\a', 'v', '\x2', 
		'\x2', '\xCC', '\xCD', '\a', 'm', '\x2', '\x2', '\xCD', '\xCE', '\a', 
		'g', '\x2', '\x2', '\xCE', '\xCF', '\a', '{', '\x2', '\x2', '\xCF', '\xD0', 
		'\a', 'u', '\x2', '\x2', '\xD0', '\x1E', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xD3', '\t', '\x2', '\x2', '\x2', '\xD2', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '\xD3', '\xD4', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD2', '\x3', 
		'\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD5', 
		' ', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xDA', '\a', '$', '\x2', '\x2', 
		'\xD7', '\xD9', '\n', '\x3', '\x2', '\x2', '\xD8', '\xD7', '\x3', '\x2', 
		'\x2', '\x2', '\xD9', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', 
		'\x3', '\x2', '\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', '\x2', 
		'\xDB', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', 
		'\x2', '\x2', '\xDD', '\xDE', '\a', '$', '\x2', '\x2', '\xDE', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\xDF', '\xE0', '\a', '&', '\x2', '\x2', '\xE0', 
		'\xE1', '\a', '}', '\x2', '\x2', '\xE1', '\xE2', '\a', 'V', '\x2', '\x2', 
		'\xE2', '\xE3', '\a', '\x43', '\x2', '\x2', '\xE3', '\xE4', '\a', '\x44', 
		'\x2', '\x2', '\xE4', '\xE5', '\a', 'N', '\x2', '\x2', '\xE5', '\xE6', 
		'\a', 'G', '\x2', '\x2', '\xE6', '\xE7', '\a', '\x7F', '\x2', '\x2', '\xE7', 
		'\xE8', '\a', '\x30', '\x2', '\x2', '\xE8', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xE9', '\xEB', '\t', '\x4', '\x2', '\x2', '\xEA', '\xE9', '\x3', 
		'\x2', '\x2', '\x2', '\xEB', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEC', 
		'\xEA', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\x3', '\x2', '\x2', 
		'\x2', '\xED', '$', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xF0', '\t', 
		'\x5', '\x2', '\x2', '\xEF', '\xEE', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF1', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xEF', '\x3', '\x2', '\x2', 
		'\x2', '\xF1', '\xF2', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\x3', 
		'\x2', '\x2', '\x2', '\xF3', '\xF4', '\b', '\x13', '\x2', '\x2', '\xF4', 
		'&', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF9', '\a', '%', '\x2', '\x2', 
		'\xF6', '\xF8', '\n', '\x3', '\x2', '\x2', '\xF7', '\xF6', '\x3', '\x2', 
		'\x2', '\x2', '\xF8', '\xFB', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xF7', 
		'\x3', '\x2', '\x2', '\x2', '\xF9', '\xFA', '\x3', '\x2', '\x2', '\x2', 
		'\xFA', '\xFC', '\x3', '\x2', '\x2', '\x2', '\xFB', '\xF9', '\x3', '\x2', 
		'\x2', '\x2', '\xFC', '\xFD', '\b', '\x14', '\x3', '\x2', '\xFD', '(', 
		'\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', '\a', '=', '\x2', '\x2', '\xFF', 
		'\x100', '\a', '=', '\x2', '\x2', '\x100', '*', '\x3', '\x2', '\x2', '\x2', 
		'\x101', '\x102', '\a', '<', '\x2', '\x2', '\x102', ',', '\x3', '\x2', 
		'\x2', '\x2', '\x103', '\x104', '\a', '}', '\x2', '\x2', '\x104', '.', 
		'\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\a', '\x7F', '\x2', '\x2', 
		'\x106', '\x30', '\x3', '\x2', '\x2', '\x2', '\t', '\x2', 'j', '\xD4', 
		'\xDA', '\xEC', '\xF1', '\xF9', '\x4', '\b', '\x2', '\x2', '\x2', '\x3', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace GraphqlToTsql.CodeGen.LookML
