//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LookML.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GraphqlToTsql.CodeGen.LookML {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LookMLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface ILookMLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.lookml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLookml([NotNull] LookMLParser.LookmlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.lookml"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLookml([NotNull] LookMLParser.LookmlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterView([NotNull] LookMLParser.ViewContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.view"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitView([NotNull] LookMLParser.ViewContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.sql_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSql_table_name([NotNull] LookMLParser.Sql_table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.sql_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSql_table_name([NotNull] LookMLParser.Sql_table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerived_table([NotNull] LookMLParser.Derived_tableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.derived_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerived_table([NotNull] LookMLParser.Derived_tableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.derived_table_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDerived_table_pair([NotNull] LookMLParser.Derived_table_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.derived_table_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDerived_table_pair([NotNull] LookMLParser.Derived_table_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] LookMLParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] LookMLParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] LookMLParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] LookMLParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.array_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_key([NotNull] LookMLParser.Array_keyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.array_key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_key([NotNull] LookMLParser.Array_keyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] LookMLParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] LookMLParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKey([NotNull] LookMLParser.KeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.key"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKey([NotNull] LookMLParser.KeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] LookMLParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] LookMLParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] LookMLParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] LookMLParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LookMLParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] LookMLParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LookMLParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] LookMLParser.CommentContext context);
}
} // namespace GraphqlToTsql.CodeGen.LookML
