//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Gql.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace GraphqlToTsql.CodeGen {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGqlListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class GqlBaseListener : IGqlListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] GqlParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] GqlParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinition([NotNull] GqlParser.DefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinition([NotNull] GqlParser.DefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.executableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecutableDefinition([NotNull] GqlParser.ExecutableDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.executableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecutableDefinition([NotNull] GqlParser.ExecutableDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.operationDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperationDefinition([NotNull] GqlParser.OperationDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.operationDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperationDefinition([NotNull] GqlParser.OperationDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.operationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperationType([NotNull] GqlParser.OperationTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.operationType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperationType([NotNull] GqlParser.OperationTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.selectionSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelectionSet([NotNull] GqlParser.SelectionSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.selectionSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelectionSet([NotNull] GqlParser.SelectionSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection([NotNull] GqlParser.SelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection([NotNull] GqlParser.SelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] GqlParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] GqlParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] GqlParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] GqlParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] GqlParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] GqlParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlias([NotNull] GqlParser.AliasContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.alias"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlias([NotNull] GqlParser.AliasContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.fragmentSpread"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFragmentSpread([NotNull] GqlParser.FragmentSpreadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.fragmentSpread"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFragmentSpread([NotNull] GqlParser.FragmentSpreadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.fragmentDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFragmentDefinition([NotNull] GqlParser.FragmentDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.fragmentDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFragmentDefinition([NotNull] GqlParser.FragmentDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.fragmentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFragmentName([NotNull] GqlParser.FragmentNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.fragmentName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFragmentName([NotNull] GqlParser.FragmentNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeCondition([NotNull] GqlParser.TypeConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeCondition([NotNull] GqlParser.TypeConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.inlineFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineFragment([NotNull] GqlParser.InlineFragmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.inlineFragment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineFragment([NotNull] GqlParser.InlineFragmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] GqlParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] GqlParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.intValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntValue([NotNull] GqlParser.IntValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.intValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntValue([NotNull] GqlParser.IntValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.floatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatValue([NotNull] GqlParser.FloatValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.floatValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatValue([NotNull] GqlParser.FloatValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.booleanValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanValue([NotNull] GqlParser.BooleanValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.booleanValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanValue([NotNull] GqlParser.BooleanValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringValue([NotNull] GqlParser.StringValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.stringValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringValue([NotNull] GqlParser.StringValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.nullValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullValue([NotNull] GqlParser.NullValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.nullValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullValue([NotNull] GqlParser.NullValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] GqlParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] GqlParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.listValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListValue([NotNull] GqlParser.ListValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.listValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListValue([NotNull] GqlParser.ListValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectValue([NotNull] GqlParser.ObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.objectValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectValue([NotNull] GqlParser.ObjectValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectField([NotNull] GqlParser.ObjectFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectField([NotNull] GqlParser.ObjectFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] GqlParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] GqlParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.variableDefinitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDefinitions([NotNull] GqlParser.VariableDefinitionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.variableDefinitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDefinitions([NotNull] GqlParser.VariableDefinitionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.variableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDefinition([NotNull] GqlParser.VariableDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.variableDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDefinition([NotNull] GqlParser.VariableDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultValue([NotNull] GqlParser.DefaultValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.defaultValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultValue([NotNull] GqlParser.DefaultValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] GqlParser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] GqlParser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.namedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamedType([NotNull] GqlParser.NamedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.namedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamedType([NotNull] GqlParser.NamedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.listType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListType([NotNull] GqlParser.ListTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.listType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListType([NotNull] GqlParser.ListTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.directives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectives([NotNull] GqlParser.DirectivesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.directives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectives([NotNull] GqlParser.DirectivesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] GqlParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] GqlParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeSystemDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSystemDefinition([NotNull] GqlParser.TypeSystemDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeSystemDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSystemDefinition([NotNull] GqlParser.TypeSystemDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeSystemExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSystemExtension([NotNull] GqlParser.TypeSystemExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeSystemExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSystemExtension([NotNull] GqlParser.TypeSystemExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.schemaDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchemaDefinition([NotNull] GqlParser.SchemaDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.schemaDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchemaDefinition([NotNull] GqlParser.SchemaDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.rootOperationTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRootOperationTypeDefinition([NotNull] GqlParser.RootOperationTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.rootOperationTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRootOperationTypeDefinition([NotNull] GqlParser.RootOperationTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.schemaExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchemaExtension([NotNull] GqlParser.SchemaExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.schemaExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchemaExtension([NotNull] GqlParser.SchemaExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.operationTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperationTypeDefinition([NotNull] GqlParser.OperationTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.operationTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperationTypeDefinition([NotNull] GqlParser.OperationTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription([NotNull] GqlParser.DescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription([NotNull] GqlParser.DescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefinition([NotNull] GqlParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefinition([NotNull] GqlParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeExtension([NotNull] GqlParser.TypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeExtension([NotNull] GqlParser.TypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.scalarTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarTypeDefinition([NotNull] GqlParser.ScalarTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.scalarTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarTypeDefinition([NotNull] GqlParser.ScalarTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.scalarTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarTypeExtension([NotNull] GqlParser.ScalarTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.scalarTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarTypeExtension([NotNull] GqlParser.ScalarTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.objectTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectTypeDefinition([NotNull] GqlParser.ObjectTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.objectTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectTypeDefinition([NotNull] GqlParser.ObjectTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.implementsInterfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplementsInterfaces([NotNull] GqlParser.ImplementsInterfacesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.implementsInterfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplementsInterfaces([NotNull] GqlParser.ImplementsInterfacesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.fieldsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsDefinition([NotNull] GqlParser.FieldsDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.fieldsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsDefinition([NotNull] GqlParser.FieldsDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.fieldDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDefinition([NotNull] GqlParser.FieldDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.fieldDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDefinition([NotNull] GqlParser.FieldDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.argumentsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentsDefinition([NotNull] GqlParser.ArgumentsDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.argumentsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentsDefinition([NotNull] GqlParser.ArgumentsDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.inputValueDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputValueDefinition([NotNull] GqlParser.InputValueDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.inputValueDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputValueDefinition([NotNull] GqlParser.InputValueDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.objectTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectTypeExtension([NotNull] GqlParser.ObjectTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.objectTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectTypeExtension([NotNull] GqlParser.ObjectTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.interfaceTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceTypeDefinition([NotNull] GqlParser.InterfaceTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.interfaceTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceTypeDefinition([NotNull] GqlParser.InterfaceTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.interfaceTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceTypeExtension([NotNull] GqlParser.InterfaceTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.interfaceTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceTypeExtension([NotNull] GqlParser.InterfaceTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.unionTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionTypeDefinition([NotNull] GqlParser.UnionTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.unionTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionTypeDefinition([NotNull] GqlParser.UnionTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.unionMemberTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionMemberTypes([NotNull] GqlParser.UnionMemberTypesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.unionMemberTypes"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionMemberTypes([NotNull] GqlParser.UnionMemberTypesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.unionTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnionTypeExtension([NotNull] GqlParser.UnionTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.unionTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnionTypeExtension([NotNull] GqlParser.UnionTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.enumTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumTypeDefinition([NotNull] GqlParser.EnumTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.enumTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumTypeDefinition([NotNull] GqlParser.EnumTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.enumValuesDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValuesDefinition([NotNull] GqlParser.EnumValuesDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.enumValuesDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValuesDefinition([NotNull] GqlParser.EnumValuesDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.enumValueDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValueDefinition([NotNull] GqlParser.EnumValueDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.enumValueDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValueDefinition([NotNull] GqlParser.EnumValueDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.enumTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumTypeExtension([NotNull] GqlParser.EnumTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.enumTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumTypeExtension([NotNull] GqlParser.EnumTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.inputObjectTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputObjectTypeDefinition([NotNull] GqlParser.InputObjectTypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.inputObjectTypeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputObjectTypeDefinition([NotNull] GqlParser.InputObjectTypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.inputFieldsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputFieldsDefinition([NotNull] GqlParser.InputFieldsDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.inputFieldsDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputFieldsDefinition([NotNull] GqlParser.InputFieldsDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.inputObjectTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInputObjectTypeExtension([NotNull] GqlParser.InputObjectTypeExtensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.inputObjectTypeExtension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInputObjectTypeExtension([NotNull] GqlParser.InputObjectTypeExtensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.directiveDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectiveDefinition([NotNull] GqlParser.DirectiveDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.directiveDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectiveDefinition([NotNull] GqlParser.DirectiveDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.directiveLocations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectiveLocations([NotNull] GqlParser.DirectiveLocationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.directiveLocations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectiveLocations([NotNull] GqlParser.DirectiveLocationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.directiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirectiveLocation([NotNull] GqlParser.DirectiveLocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.directiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirectiveLocation([NotNull] GqlParser.DirectiveLocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.executableDirectiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExecutableDirectiveLocation([NotNull] GqlParser.ExecutableDirectiveLocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.executableDirectiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExecutableDirectiveLocation([NotNull] GqlParser.ExecutableDirectiveLocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.typeSystemDirectiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeSystemDirectiveLocation([NotNull] GqlParser.TypeSystemDirectiveLocationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.typeSystemDirectiveLocation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeSystemDirectiveLocation([NotNull] GqlParser.TypeSystemDirectiveLocationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GqlParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] GqlParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GqlParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] GqlParser.NameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace GraphqlToTsql.CodeGen
